exports.errorCatch = (err) => {
  console.log("Ooops", err);
};
